### PR TITLE
n queens problem in python for 4 queens

### PR DESCRIPTION
**Pull request by talkshrey**
Hey can I contribute under hacktober fest label, this code is in python. Thank you!

### CODE REVIEW

**Review by PythonicBoat — COMMENTED** [review]
The code looks good, can you make it for N number of queens?

**Review by PythonicBoat — APPROVED** [review]
looks good

**Comment by talkshrey** [comment]
can you add hacktober fest label for it so that it counts?

**Comment by PythonicBoat** [comment]
This repository already has the hacktoberfest tag

**Pull request merged**
